### ISSUE TITLE
能用三方框架加载吗    因为感觉加载大图片的时候有点慢  想体高加载速度   还有想添加加载动画

### ISSUE THREAD

**Issue by wukuiqing49** [EvilBT/HDImageView#2]

**Comment by EvilBT** [comment]
@wukuiqing49 加载http://或者https://的图片是可以用第三方加载框架加载的，具体看一下我的MainApplication中注释掉的代码。加载动画的话，可以在设置图片资源的时候添加一个图片加载监听，具体看一下源码。
