### ISSUE TITLE
默认的配置下，图片较小的情况下无法缩放

### ISSUE THREAD

**Issue by imyyq-star** [EvilBT/HDImageView#8]
如果图片很小的话，显示出来无法进行双指缩放和双击缩放，请问要如何配置才能对较小的图片进行缩放？

期望：
一开始显示初始大小，然后用户可自行缩放，越大越好

**Comment by EvilBT** [comment]
mImageView = (HDImageView) findViewById(R.id.image);

        mImageView.setMaxScale(20f);

        mImageView.setMinScale(1f);

        mImageView.setDoubleTapZoomScale(10F);

        mImageView.setScaleType(CUSTOM);
这样的话就是初始是图片大小，小图也可以强制缩放的了，范围就在min~max之间，scaleType会影响最小缩放的值，你可以自己调整一下参数。
